# Generated by Django 5.1.15 on 2026-09-15 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='call', max_length=20)),
                ('looking_for', models.CharField(blank=True, default='Rent', max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('bhk', models.CharField(blank=True, db_index=True, max_length=30)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('preferred_area', models.CharField(blank=True, max_length=150)),
                ('min_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('max_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(blank=True, max_length=50)),
                ('move_in_date', models.CharField(blank=True, help_text='e.g. Immediately, Within 15 Days, Next Month', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Specific requirements, pet preferences, parking need, etc.')),
                ('source', models.CharField(db_index=True, default='Website', max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=150)),
                ('utm_medium', models.CharField(blank=True, max_length=150)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit_scheduled', 'Visit Scheduled'), ('negotiation', 'Negotiation'), ('converted', 'Converted (Deal Closed)'), ('not_interested', 'Not Interested'), ('closed', 'Closed / Lost')], db_index=True, default='new', max_length=30)),
                ('admin_remark', models.TextField(blank=True, help_text='Internal notes by sales/leasing team')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Sales representative handling this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Specific property being enquired about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='properties.property')),
            ],
            options={
                'verbose_name': 'Enquiry & Lead',
                'verbose_name_plural': 'Enquiries & Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='enquiries_e_status_91f4fd_idx'), models.Index(fields=['city', 'bhk'], name='enquiries_e_city_f50c6a_idx')],
            },
        ),
    ]
