# Generated by Django 5.1.15 on 2026-09-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='bi-check-circle', help_text="Bootstrap Icon class, e.g., 'bi-car-front', 'bi-lightning-charge', 'bi-shield-check'", max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Editorial overview of the neighbourhood.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['city', 'area'],
                'unique_together': {('city', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Descriptive title e.g. 'Spacious 2 BHK Flat in Sector 62'", max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('independent_floor', 'Independent Floor'), ('villa', 'Villa / House'), ('studio', 'Studio Apartment'), ('penthouse', 'Penthouse')], db_index=True, default='flat', max_length=30)),
                ('bhk', models.CharField(choices=[('1_rk', '1 RK'), ('1_bhk', '1 BHK'), ('2_bhk', '2 BHK'), ('3_bhk', '3 BHK'), ('4_bhk', '4 BHK'), ('5_bhk_plus', '5+ BHK')], db_index=True, default='2_bhk', max_length=20)),
                ('description', models.TextField(help_text='Detailed property description, layout specs, and tenant preferences.')),
                ('rent', models.PositiveIntegerField(db_index=True, help_text='Monthly rent in Indian Rupees (INR)')),
                ('security_deposit', models.PositiveIntegerField(default=0, help_text='Security deposit in INR')),
                ('maintenance_charges', models.PositiveIntegerField(default=0, help_text='Monthly maintenance charges in INR (if any)')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sqft', models.PositiveIntegerField(help_text='Super built-up or carpet area in sq. ft.')),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('bathrooms', models.PositiveSmallIntegerField(default=2)),
                ('balconies', models.PositiveSmallIntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], db_index=True, default='semi_furnished', max_length=30)),
                ('parking', models.CharField(choices=[('none', 'None'), ('two_wheeler', 'Two-Wheeler Only'), ('1_car', '1 Covered Car Parking'), ('2_cars', '2 Covered Car Parkings'), ('open_parking', 'Open Parking')], default='1_car', max_length=30)),
                ('floor_no', models.CharField(blank=True, default='4th of 14', max_length=20)),
                ('facing', models.CharField(blank=True, default='North-East', max_length=30)),
                ('age_of_property', models.CharField(blank=True, default='0-3 Years', max_length=50)),
                ('available_from', models.DateField(blank=True, help_text='Date from which property is ready for move-in', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show in featured carousel/cards')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('location', models.ForeignKey(blank=True, help_text='Linked city and area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility & SEO', max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['display_order', '-is_primary', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'bhk', 'status'], name='properties__city_2a95f4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent', 'status'], name='properties__rent_c92a64_idx'),
        ),
    ]
