# Generated by Django 5.1.15 on 2026-09-15 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign name or promotional headline', max_length=200)),
                ('image', models.ImageField(help_text='Promotional banner asset', upload_to='advertisements/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Subtext or promotional callout')),
                ('target_url', models.URLField(blank=True, help_text='Destination URL (if not directly linked to a property). Can include UTM parameters.')),
                ('placement', models.CharField(choices=[('homepage_hero', 'Homepage Hero'), ('homepage_banner', 'Homepage Banner'), ('property_listing', 'Property Listing Top/Inline'), ('property_detail', 'Property Detail Sidebar'), ('sidebar', 'General Sidebar'), ('popup', 'Lead Modal / Popup')], db_index=True, default='homepage_banner', max_length=40)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Campaign start date')),
                ('end_date', models.DateField(blank=True, help_text='Campaign expiration date (optional)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, help_text='Optional: direct link to a featured property listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Click',
                'verbose_name_plural': 'Advertisement Clicks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
